pipeline:
  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push
        - pull_request
#  build_and_deploy_code:
#    image: maven
#    when:
#      branch: [master, develop]
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    secrets: [ access_key, access_key_id ]
#    commands:
#      - ./build-deploy.sh
#  notify_slack:
#    image: plugins/slack
#    webhook: https://hooks.slack.com/services/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
#    channel: builds
#    when:
#      status: [success, failure]
